TP5 : badge checkstyle

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -43,35 +43,27 @@ jobs:
           name: Run Checkstyle
           command: |
             
-            echo 1
             mvn checkstyle:check || true
-            echo 2
-            error_count=$(grep -o '<error ' target/checkstyle-result.xml | wc -l)
-            echo 3
+            error_count=$(grep -o '<error ' target/checkstyle-result.xml | wc -l || echo 0)
+            
+            echo "error : " + ${error_count}
             
             if [ "$error_count" -eq 0 ]; then
             badge_color="brightgreen" 
             else
             badge_color="red" 
             fi
-            echo 4
             
             git config --global user.email "yassinebouazzati2@gmail.com"
             git config --global user.name "BZT-T"
-            echo 5
             git pull origin master || true
-            echo 6
-            echo "error : " + ${error_count}
+            
             sed -i "s|https://img.shields.io/badge/Checkstyle_Errors-[0-9]*-[a-z]*|https://img.shields.io/badge/Checkstyle_Errors-${error_count}-${badge_color}|" README.md
-            echo 7
             if git diff --quiet README.md; then
                 echo "No changes in README.md, skipping commit."
             else
-                echo 8
                 git add README.md
-                echo 9
                 git commit -m "Update README with Checkstyle error count [skip ci]"
-                echo 10
                 git push
             fi
 
